### ISSUE TITLE
selfcheck err

### ISSUE THREAD

**Issue by smartwe** [331leo/hcskr_python#32] opened 2021-09-04 12:20 UTC
원래는 잘됬었다가 일주일 전인가 그부터는 Traceback (most recent call last):
  File "/home/runner/work/module-used-jagajindan/module-used-jagajindan/main.py", line 6, in <module>
    hcskr.selfcheck(std1[0], std1[1], std1[2], std1[3], std1[4], std1[5])
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/hcskr/hcs.py", line 24, in selfcheck
    return loop.run_until_complete(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/hcskr/hcs.py", line 91, in asyncSelfCheck
    login_result = await asyncUserLogin(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/hcskr/hcs.py", line 232, in asyncUserLogin
    school_infos = await search_school(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/hcskr/request.py", line 35, in search_school
    return await resp.json()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://hcs.eduro.go.kr/v2/searchSchool?lctnScCode=01&schulCrseScCode=2&orgName=%EB%AA%A9%EC%9A%B4%EC%B4%88&loginType=school')
이런 에러가 뜨네요ㅜㅜ

**Comment by penggin** [comment] 2021-09-04 12:23
@smartwe 
Duplicate of #31

**Comment by smartwe** [comment] 2021-09-04 12:28
근데 100개중에 20~30개가 아니고 할때 마다 안되는건......
믕...

**Closed** 2021-09-04 12:27 UTC

**Comment by penggin** [comment] 2021-09-04 12:34
@smartwe 
앗 잘못적었었네요
#31 이 아닌, #29 입니다!

**Comment by smartwe** [comment] 2021-09-04 12:36
ㅇㅎ 막았나보네용ㅎㅎ
